### ISSUE TITLE
Add `.textlintignore` support to `lintText()`

### ISSUE THREAD

**Issue by frozenbonito** [textlint/textlint#1408]
This is a feature request.

Currently, `lintText()` does not respect `.textlintignore`.
https://github.com/textlint/textlint/blob/80cea10d17d7b874e332fd0bc756216bb016d9f1/packages/textlint/src/createLinter.ts#L83-L90

I think this behavior is appropriate, but [vscode-textlint](https://github.com/taichi/vscode-textlint) expects this method to have ignore file support, so it won't work properly.
https://github.com/taichi/vscode-textlint/issues/68

https://github.com/taichi/vscode-textlint/blob/79225a379b2e73ab227d6e862b99f0cc586c88e9/packages/textlint-server/src/server.ts#L98-L101
https://github.com/taichi/vscode-textlint/blob/79225a379b2e73ab227d6e862b99f0cc586c88e9/packages/textlint-server/src/server.ts#L332

Previously, when I added ignore file support to vscode-textlint, I implemented the same ignore logic as textlint because `executeOnText()` (in textlint v11) does not have ignore file support.
https://github.com/taichi/vscode-textlint/pull/22

This approach was ugly and was later refactored into the current implementation.
https://github.com/taichi/vscode-textlint/commit/8ee34bcdd9be7debc6f38e1af68f4b2a5b55a272

This change seems to have broken ignore file support, but I agree that vscode-textlint should use textlint's ignore logic directly.
Currently, `lintText()` receives the target file path, so it is also possible to ignore the file.
To avoid breaking changes, `CreateLinterOption` may need a flag to enable this feature.

**Comment by azu** [comment]
Hmm, I am aware that `filePath` in `lintText` is just a Hint string or virtual file path.
In other words, this `filePath` may not be real, so I'm not sure if it's subtle to implement IGNORE assuming the file actually exists.
The `lintFiles` supports ignore.
Can't `lintFiles` fulfill your requirement?

**Comment by frozenbonito** [comment]
Thank you for comment.
I will try using `lintFiles()`.

**Comment by frozenbonito** [comment]
@azu 
I tried using it.

`lintFiles()` doesn't seem to ignore it when it receives a filename rather than a pattern.
https://github.com/textlint/textlint/blob/5eab05f365db6e5fdf3b1981a17772f31e559d36/packages/textlint/src/util/find-util.ts#L78-L80

Therefore, it will not work as expected when used with vscode-textlint.
How about adding a flag to CreateLinterOption (and FindFilesOptions) to change this behavior?

**Comment by azu** [comment]
## Summary

- Rewrite find-utils to fix the problem of file paths not being ignored
  - I think it would be better to make this a destructive change
  - I can't think of a use case where I don't want to ignore it.
- Add `isPathIgnored(filePath)` - checks if a given file path is ignored

## Migration Step

We can take the following steps to proceed step by step

1. Implement new find-utils with globby
2. Add `linter.isPathIgnored()` - use new find-utils, `linter.lintFile()` use old find-utils yet
3. MINOR release
4. Use new find-utils in textlint - `linter.lintFile()` use new find-utils
5. MAJOR release

## Details

There three problems with textlint's ignore feature.

1. Does not have an API to determine if a file path is ignored
2. When passing file paths, ignore is not applied
3. [Additional] Behavior issues when ignored

### 1 Problem with No ignore API

Issue: https://github.com/textlint/textlint/issues/1408

**Conclusion:** Add [isPathIgnored](https://eslint.org/docs/latest/integrate/nodejs-api#-eslintispathignoredfilepath) API

- I think it's reasonable that linter.lintText does not ignore
    - In textlint, `option.filePath` assumes a pseudo file
    - It is used to determine which parser to use, similar to Content Type
- If you want to ignore in lintText, using isPathIgnored(path) might be good
    - Currently, textlint does not exporse [isPathIgnored](https://eslint.org/docs/latest/integrate/nodejs-api#-eslintispathignoredfilepath)-like API
- lintText(1 file) and isPathIgnored(1 file) are balanced
- On the other hand, lintFiles(multiple files) makes isPathIgnored difficult to use
    - → lintFiles itself has built-in ignore, so it is not used

### 2 Problem with not ignoring when passing file paths

**Conclusion:** find-utils need to be rewritten. It's difficult to do without BREAKING CHANGE

Issue: None yet

- Currently, when passing file paths, ignore is not applied
- Ignore is only effective for glob

Problem: There is no way to ignore when linting by passing file paths

- In the case of CLI, it was not much of a problem because specifying and passing file paths was intentional
- In the case of API, it is difficult without a way to avoid this

What to do:

- Currently, textlint has a custom implementation with `glob`, it would be better to migrate this to [globby](https://github.com/sindresorhus/globby)
    - https://github.com/textlint/textlint/blob/80cea10d17d7b874e332fd0bc756216bb016d9f1/packages/textlint/src/util/find-util.ts#L50
    - It would also be good to add gitignore support at the same time
- Related issue:
  - https://github.com/secretlint/secretlint/pull/672
  - https://github.com/secretlint/secretlint/issues/337

It will resolve:

- Ignore will be applied even when passing file paths
- Compatibility with gitignore will increase
- [isPathIgnored](https://eslint.org/docs/latest/integrate/nodejs-api#-eslintispathignoredfilepath) can be implemented

It will changes the behavior:

- Ignore the file path which is ignored by textlintignore when passing the file path via API/CLI

### 3 Behavior issues when ignored

Issue: https://github.com/textlint/textlint/issues/226

- Even if ignored, it is not possible to determine from CLI or API whether it was intentionally passed or not
- e.g. In the case of a specification like `test/**/*.md`, if the test directory is empty, it is not possible to determine whether it is 0 because everything was ignored or simply because there are no files in the test directory yet
    - In ESLint, this can be controlled with a flag called [--no-warn-ignored](https://eslint.org/docs/latest/use/command-line-interface#--no-warn-ignored)
    - This method is a bit worrisome
- The problem is that if it is 0 unintentionally = when the directory name is wrong, a warning should be issued
    - → In other words, linting against non-existent cases should be a warning
    - For users, it means that it should have been linted but was not
    - It would be good to have a mechanism to notice this
- There are cases where it is okay to warn in combination
    - Unsupported extension + specified file path → can issue that it is not supported
    - Included in textlintignore + specified file path → can issue a warning because it is a file path
        - In the case of glob, it is not possible to distinguish whether it is intentional or not
- Mistake between glob expanded by shell and glob string
    - `textlint **/*.md` and `textlint "**/*.md"` are different from the program's perspective
    - The former passes the file path because the shell expands the glob
    - The latter passes the glob string
    - This problem complicates the issue

|  | File Path | Glob | File Path Expanded by Shell |
| --- | --- | --- | --- |
| Unsupported Extension | Warning | No | Warning |
| Ignored Path | Warning | No | Warning |
| Non-existent Directory | Error | No | Error |
| Non-existent Path | Error | No | Error |

**Comment by frozenbonito** [comment]
@azu 
Thank you for your consideration.
The above ideas seem very good to me.
I think the `isPathIgnored` API would solve the vscode-textlint issue.

**Comment by azu** [comment]
Close by merging to #1409

**Comment by azu** [comment]
Fixed in https://github.com/textlint/textlint/releases/tag/v14.1.0
