### ISSUE TITLE
Run build before document linting

### ISSUE THREAD

**Issue by 0x6b** [textlint/textlint#381]
Hi, while creating a documentation pull request for #377, I started with fresh clone and found place for improvement in the [contributing guideline](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#integration-test).

**What version of textlint are you using?**

v9.1.1

**What file type (Markdown, plain text, etc.) are you using?**

N/A

**What did you do? Please include the actual source code causing the issue.**

- Fork the repo at [GitHub](https://github.com).
- Clone the repo locally: `git clone https://github.com/0x6b/textlint`
- `cd` to local directory: `cd textlint`
- Install dependencies: `yarn install`
- Bootstrap packages: `yarn run bootstrap`
- Fix document and commit change.
- Run the tests following [Fixing document](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#fixing-document): `yarn run lint` -- failed with `Cannot find module '../lib/textlint/src/cli'`

**What did you expect to happen?**

`lint` package script finished without error.

**What actually happened? Please include the actual, raw output from textlint.**

```sh
> yarn run lint
yarn run v1.3.2
$ npm-run-all --parallel textlint eslint
$ node packages/textlint/bin/textlint.js --cache -c docs/.textlintrc docs/ .github/ README.md -f pretty-error
$ eslint --cache 'packages/*/src/**/*.js'
module.js:544
    throw err;
    ^

Error: Cannot find module '../lib/textlint/src/cli'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/.../textlint/textlint/packages/textlint/bin/textlint.js:11:11)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
error Command failed with exit code 1.
```

Simply run `yarn run clean && yarn run lint` will reproduce the issue.

To solve the issue:

1. Update `package.json`: add `"prelint": "npm run build"`, or
2. Update [Fixing document](https://github.com/textlint/textlint/blob/a4688b99896aba26a064a081c34115acb943295e/.github/CONTRIBUTING.md#fixing-document) section: run `npm run build` before `npm run lint`

Any other idea?
(It would be good to replace all `npm` with `yarn` for consistency but that might be another story.)

Thank you.

**Comment by azu** [comment]
Thanks for suggestion 👍 

> 1. Update package.json: add "prelint": "npm run build",
 
It is reasonable.
But, It has also a bit difficult context.
Because, we already defined `npm run build`  in `pretest`.

https://github.com/textlint/textlint/blob/c79e3b6914166e899148b53f18e1f55cdb8e3edb/package.json#L16

Current: `npm test`

1. npm run build
2. npm run lint
3. npm run test:packages

If add `"prelint": "npm run build"`

1. npm run build
2. npm run build
3. npm run lint
4. npm run test:packages

We want to avoid this duplicated build.

If you have an idea to resolve this duplicated build issue, we can select pattern **1**.

> 2. Update Fixing document section: run npm run build before npm run lint

If there are no idea, we will select pattern **2**

Other idea, add `npm run build` to `npm run bootstrap`

`"bootstrap": "lerna bootstrap && npm run build",`
But, it can not resolve `yarn run clean && yarn run lint` pattern.
https://github.com/textlint/textlint/blob/c79e3b6914166e899148b53f18e1f55cdb8e3edb/package.json#L14

**Comment by 0x6b** [comment]
@azu, thank you for your detailed analysis. I haven't noticed that duplication. I think using task runner might help this case but it will introduce another complexity and raise the bar for new comers. I prefer pattern 2 for its simplicity.

**Comment by azu** [comment]
> I prefer pattern 2 for its simplicity.

I agree.
