### ISSUE TITLE
website: Update sidebar.json

### ISSUE THREAD

**Issue by azu** [textlint/textlint#466]
From #461 

## Tasks

- Flat docs/*.md
   - This is a limitation of [Support sub-directories in docs/ · Issue #323 · facebook/Docusaurus](https://github.com/facebook/Docusaurus/issues/323 "Support sub-directories in docs/ · Issue #323 · facebook/Docusaurus")
   - Preserve [textlint/docs/faq/](https://github.com/textlint/textlint/tree/master/docs/faq "textlint/docs/faq/") (This is linked from source code)
- Add `id` to each docs/*.md
- Update sidebar.json
   - [Adding Documents to a Sidebar](https://docusaurus.io/docs/en/navigation.html#adding-documents-to-a-sidebar "Adding Documents to a Sidebar")

## Docusaurus Limitation
Current limitation: [Support sub-directories in docs/ · Issue #323 · facebook/Docusaurus](https://github.com/facebook/Docusaurus/issues/323 "Support sub-directories in docs/ · Issue #323 · facebook/Docusaurus")

**Comment by 0x6b** [comment]
@azu, how about moving [CONTRIBUTING.md](https://github.com/textlint/textlint/blob/69e47c7aadd48217dc29c53e789263d5671943a5/.github/CONTRIBUTING.md) to `docs` folder while maintaining document structure? I found that [this commit](https://github.com/textlint/textlint/commit/8257fc86b7c8f0b5f7bde1dba03858dfbff1c818#diff-8cc7b2b0d78dd2501610391c086a8516) moved contribution guideline from project root to `.github` directory, but since this guideline is not specific for GitHub, I think `docs` is better place.

Note that GitHub could find it under `docs` according to the [document](https://help.github.com/articles/setting-guidelines-for-repository-contributors/).

> To help your project contributors do good work, you can add a file with contribution guidelines to your project repository's root, `docs`, or `.github` folder. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file.

**Comment by azu** [comment]
> how about moving CONTRIBUTING.md to docs folder while maintaining document structure?

Yes please.
