### ISSUE TITLE
Feature Suggestions: textlint-plugin supports binary format

### ISSUE THREAD

**Issue by heriet** [textlint/textlint#649]
**What version of textlint are you using?**
v11.5.0

**What file type (Markdown, plain text, etc.) are you using?**
etc(binary file type)

**What did you do? Please include the actual source code causing the issue.**

I’m thinking of create [textlint-plugin for pptx](https://github.com/heriet/textlint-plugin-pptx). The pptx is binary file format. So, textlint can't load decoded `text` from pptx file.

A textlint-plugin for binary format will return correct TxtAST, but textlint kernel's [getSource](https://github.com/textlint/textlint/blob/textlint%4011.5.0/packages/@textlint/kernel/src/context/TextlintSourceCodeImpl.ts#L87) generates source from file `text`. That has lead to textlint-plugin for binary format is not work.

**What did you expect to happen?**

I suggest that [getSource](https://github.com/textlint/textlint/blob/textlint%4011.5.0/packages/@textlint/kernel/src/context/TextlintSourceCodeImpl.ts#L87) generates source from `node.raw`. If `beforeCount` or `afterCount` is inputed, getSource generetes source from `parent node.raw`.

textlint-plugin-pptx returns following AST.

```
{
  type: 'Document',
  raw: 'hoge'
  ...
}
```

and prh rule.

```
rules:
  - expected: fuga
    patterns:
      - hoge
```

Expected

```
$ textlint example.pptx
example.pptx
  1:1   ✓ error  hoge => fuga  prh
✖ 1 problems (1 errors, 0 warnings)
```

**What actually happened? Please include the actual, raw output from textlint.**

textlint is not work because getSource returns from `text` (encoded binary) and textlint rules using getSource.

```
$ textlint example.pptx
```

**Note**

- If textlint don't want to support textlint-plugin for binary format file, we can also choose alternateve way that is convert binary format to markdown before textlint.
- `--fix` will not work textlint-plugin for binary format. but I think it is small problem.
- Alternateve way for support binary format is extending textlint-plugin Processor. For example,  Processor preProcess returns decoded text for source. But I think it may be difficult.

**Comment by azu** [comment]
My understand that [textlint-plugin-pptx](https://github.com/heriet/textlint-plugin-pptx) does following:

> **Figure A:**
> Original File(Binary) -> Pseudo-text -> TxtAST for Pseudo-text 

In this case, TxtAST is not matched for Original File(binary).
Also, `getSource` use Original File(binary) as source and return invalid results.

I think that we have two approach for resoving this issue:

1. ` getSource` depended on `TxtAST` instead of Original file (@heriet suggested)
2.  Allow plugin's `preProcess` function to return `{ text, ast }`

Details of Approach 2

Currently, plugin's `preProcess` only return a TxtAST.

https://github.com/textlint/textlint/blob/3b2ed27d200dbf5567843563b8d1b8a03eb1ebda/packages/%40textlint/types/src/Plugin/TextlintPluginModule.ts#L35

So, textlint-kernel does not know `Pseudo-text` in Figure A.

> Original File(Binary) -> Pseudo-text -> TxtAST for Pseudo-text 

Approach 2 allow textlint-kernel to know Pseudo-text by returing `{ text, ast }`

```diff
export declare class TextlintPluginProcessor {
    constructor(options?: TextlintPluginOptions);

    /**
     * Return available extensions for this plugin.
     * This extension should start with `.`(dot).
     * Example is [".md", ".mkd"]
     */
    availableExtensions(): Array<string>;

    processor(
        extension: string
    ): {
-        preProcess(text: string, filePath?: string): TxtParentNode;
+        preProcess(text: string, filePath?: string): TxtParentNode | { text: string, ast: TxtParentNode};
        postProcess(messages: Array<any>, filePath?: string): { messages: Array<any>; filePath: string };
    };
}
```

As a result, textlint-kernel can get Pseudo-text from the plugin.
All that text-kernel use the `text` that returned from the plugin.

```diff
- const ast = preProcess(text, filePath);
+ const { text, ast } = preProcess(text, filePath);
```

https://github.com/textlint/textlint/blob/cd9adbe7b63ea688a73372f0e6e4fa36bfe0332a/packages/%40textlint/kernel/src/textlint-kernel.ts#L141-L147

I think that this approach is safe, because textlint can not handle binary format.
This approach make textlint(kernel) always handle text format.

@heriet So what do you think?

**Comment by azu** [comment]
I've implemented approach 2 for POC
https://github.com/textlint/textlint/pull/650

**Comment by heriet** [comment]
Thanks!! and Excellent job!!

I also think Approach 2 is smart and the best.

I tried #650 and https://github.com/heriet/textlint-plugin-pptx/pull/1. it works as expected as well.

```
# textlint example.pptx

/work/textlint-plugin-pptx/example/example.pptx
  5:9  ✓ error  textlnt => textlint  prh

✖ 1 problem (1 error, 0 warnings)
✓ 1 fixable problem.
Try to run: $ textlint --fix [file]
```

**Comment by azu** [comment]
Thank you for confirming.

Ok. we will merge it and release it.

**Comment by azu** [comment]
Release https://github.com/textlint/textlint/releases/tag/textlint%4011.6.0
