### ISSUE TITLE
What is ParagraphExit?

### ISSUE THREAD

**Issue by nzt** [textlint/textlint#664]
Hi, there!

This is not bug report, and this is a question about `@textlint/ast-node-types`.
That package several node types related to markdown syntax.
However, that package also contains `ParagraphExit` used in nowhere. 

Why such types are provided?
Since it makes the developer misslead, I suggest to remove them if you have no reason.

Thank you.

**Comment by azu** [comment]
`*:exit` is not actual AST node's type.
The rule creator use `Syntax.DocumentExit` instead of `${Syntax.Paragrap}:exit`.
https://github.com/textlint/textlint/issues/267
It is just constant value for `*:Exit`

`Exit` constant is for traversing of AST.
https://textlint.github.io/docs/rule.html#docsNav

**Comment by nzt** [comment]
I see. Thank you for explanation.
Could you add some note in JSDOC about this topic?

**Comment by nzt** [comment]
I should notice you that eslint will report warning when we write switch-case clause for ASTNodeTypes even if we did not use.  Thus, we should write the rule for each node types or `default:` now. In my feeling, this is  unintuitive.

https://github.com/typescript-eslint/typescript-eslint/pull/972/files
