### ISSUE TITLE
Table in ast-node-types

### ISSUE THREAD

**Issue by tani** [textlint/textlint#740]
**What version of textlint are you using?**

`@textlint/ast-node-types` 4.4.1

**What file type (Markdown, plain text, etc.) are you using?**

Anything

**What did you do? Please include the actual source code causing the issue.**

I imported type definitions like Table.

**What did you expect to happen?**

We should define actual node types in ast-node-types.

**What actually happened? Please include the actual, raw output from textlint.**

```ts
import {Table, TableRow, TableCell} from "@textlint/ast-node-types"
```

ref: https://github.com/textlint/textlint-plugin-latex2e/issues/69

**Comment by kn1cht** [comment]
FYI, the developers of `textlint-plugin-review` also pointed out that there is no definition of table nodes.

https://github.com/orangain/textlint-plugin-review/pull/6

They used a workaround that uses ListItem nodes to represent table cells.

**Comment by azu** [comment]
markdown parser in texltint defined Table, TableRow, TableCell as extensions.
https://github.com/textlint/textlint/blob/a088520447cf557ccbc5d08bb481f5b8bc33d2dd/packages/%40textlint/markdown-to-ast/src/mapping/markdown-syntax-map.ts#L26-L31

The reason is that They are not defined in [CommonMark Spec](https://spec.commonmark.org/). (They are gfm extension)

However, various parser parse table syntax actually.
So, it may be reasonable that `@textlint/ast-node-types` defined `Table, TableRow, TableCell`

I'm ok that we add  `Table, TableRow, TableCell` to "@textlint/ast-node-types".

📝 I have never written a rule that uses `Table`, `TableRow`, `TableCell` directoly.

**Comment by tani** [comment]
Oh, this is an extension. I got it. Thank you for replying.
I have never thought the textlint allows other node types as extensions.
It's interesting. CommonMark is also one dialect of Markdown.

As you know, there is a so long history about Markdown dialect. Covering various syntax is a nice feature for working on Markdown. Please consider it.

**Comment by azu** [comment]
textlint just pass through an unknown node's type.

For example, a parser creates `Example` type, and textlint pass the `Example` node to each rule.

```js
// A rule can treat Example node
export default () => {
  return {
    ["Example"](node){
    }
  }
}
```

`"@textlint/ast-node-types"` just define constant value for basic node types.
Probably, it is not related to processing logic in textlint.
In other words, textlint does not drop unknown node type.

**Comment by azu** [comment]
I've created a related issue https://github.com/textlint/textlint/issues/764
We need to introduce individual Node type before adding `Table` type.
